- name: check required packages
  apt:
    name:
      - prometheus
    state: present

- name: check prometheus config
  template:
    src: templates/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: prometheus-restart

- name: check prometheus unit
  template:
    src: templates/prometheus.service.j2
    dest: /lib/systemd/system/prometheus.service
  notify: prometheus-restart

- name: ensure prometheus service is enabled and started
  systemd:
    name: prometheus
    state: started
    enabled: true
    masked: false
